version: '3.7'
services:
  session-token-manager:
    image: bobcrutchley/session-manager:latest
    build: 
      context: .
      args:
      - AUTHOR=bob-crutchley
      - PROJECT=session-token-manager
    depends_on:
    - aes-crypto
    - session-token-redis
  aes-crypto:
    image: bobcrutchley/aes-crypto:latest
  session-token-redis:
    image: redis:latest
  
